<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Zakia - Proposal with a Twist</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: 'Courier New', monospace;
      background-color: black;
      color: red;
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh;
      text-align: center;
      flex-direction: column;
      overflow: hidden;
    }

    #horror {
      font-size: 2em;
      animation: blink 0.6s infinite alternate;
    }

    @keyframes blink {
      from { opacity: 1; }
      to { opacity: 0.2; }
    }

    #main, #shayari {
      display: none;
      flex-direction: column;
      align-items: center;
      text-align: center;
    }

    h1 {
      font-size: 2.5em;
      color: #ff5e78;
      text-shadow: 0 0 10px white;
    }

    .chat-box {
      margin-top: 20px;
      background: rgba(255,255,255,0.1);
      color: white;
      padding: 20px;
      border-radius: 15px;
      width: 300px;
      box-shadow: 0 0 10px rgba(255,255,255,0.3);
    }

    button {
      margin-top: 25px;
      padding: 15px 30px;
      background: #ff4d6d;
      color: white;
      font-size: 1em;
      border: none;
      border-radius: 30px;
      cursor: pointer;
      box-shadow: 0 0 15px #fff;
    }

    #shayari {
      margin-top: 30px;
      background-color: rgba(0,0,0,0.3);
      padding: 20px;
      border-radius: 10px;
      color: #fff;
      border: 1px solid pink;
    }

    canvas {
      position: fixed;
      top: 0;
      left: 0;
      z-index: 999;
      pointer-events: none;
    }
  </style>
</head>
<body>

  <div id="horror">Zakia... RUN! Something is behind you! 👻</div>

  <!-- Sweet Part Starts -->
  <div id="main">
    <h1>Just Kidding Zakia 💖</h1>
    <div class="chat-box">
     <h3>Main hoon XYZ... aur main sirf ek hi cheez chahta hu..<br>
      <b>Tumhari Mohabbat 💌</b><br><br>
        <i>kyunki<br>
      <i>Mere usdaat ji ne kaha tha:<br> "Mohabbat karne waale kabhi darte nahi... aur jo darte hain wo mohabbat nahi karte..."</i></h3>
    </div>
    <button onclick="showShayari()">Will You Be Mine Forever? 💍</button>
  </div>

  <!-- Shayari -->
  <div id="shayari">
    <h2><p>
      "Thank You So Much Meri Jaan...<br>I Love You Zakia 💖"
    </p></h2>
  </div>

  <!-- Fireworks -->
  <canvas id="fireworks"></canvas>

  <!-- Audio Elements -->
  <audio id="horrorSound" onetime>
    <source src="horrorr.mp3" type="audio/mpeg">
  </audio>
  <audio id="romanticMusic" loop>
    <source src="romantic.mp3" type="audio/mpeg">
  </audio>

  <script>
    const horrorDiv = document.getElementById("horror");
    const mainDiv = document.getElementById("main");
    const romanticMusic = document.getElementById("romanticMusic");

    setTimeout(() => {
      horrorDiv.style.display = "none";
      document.body.style.background = "linear-gradient(to right, #ff758c, #ff7eb3)";
      mainDiv.style.display = "flex";
    }, 5000);

    function showShayari() {
      document.getElementById("shayari").style.display = "block";
      startFireworks();
      romanticMusic.play(); // Background music starts only after interaction
    }

    // 🎆 Fireworks
    const canvas = document.getElementById("fireworks");
    const ctx = canvas.getContext("2d");
    canvas.width = window.innerWidth;
    canvas.height = window.innerHeight;
    let particles = [];

    function startFireworks() {
      for (let i = 0; i < 100; i++) {
        particles.push({
          x: canvas.width / 2,
          y: canvas.height / 2,
          radius: Math.random() * 3 + 2,
          color: `hsl(${Math.random() * 360}, 100%, 50%)`,
          speedX: Math.random() * 6 - 3,
          speedY: Math.random() * 6 - 3
        });
      }
      animate();
    }

    function animate() {
      ctx.clearRect(0, 0, canvas.width, canvas.height);
      for (let i = 0; i < particles.length; i++) {
        let p = particles[i];
        ctx.beginPath();
        ctx.arc(p.x, p.y, p.radius, 0, Math.PI * 2);
        ctx.fillStyle = p.color;
        ctx.fill();
        p.x += p.speedX;
        p.y += p.speedY;
        p.radius *= 0.96;
        if (p.radius < 0.5) {
          particles.splice(i, 1);
          i--;
        }
      }
      if (particles.length > 0) requestAnimationFrame(animate);
    }
  </script>

</body>
</html>
